version: '3.3'

services:
    db_mapping:
        build: db_mapping
        ports:
            - "27017:27017"
        volumes:
            - ./mongo_data:/data 

    db_mapping_seed:
        build: db_mapping_seed
        links:
            - db_mapping
        volumes:
            - ./mongo_data:/data

    webapp:
        build: webapp
        expose:
            - 3000
        ports:
            - "3000:3000"
        stdin_open: true
        links:
            - db_mapping
        environment:
            - MONGO_HOST=db_mapping
            - PORT=27017
